/**
 * Creates 100 minimal PNG placeholders and src/assets/imageMap.js
 * Run: node scripts/generate-images.js
 */
const fs = require('fs');
const path = require('path');

// 2x2 blue pixel PNG (valid, tiny)
const PNG_BASE64 =
  'iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAYAAABytg0kAAAAGklEQVR42mP8z/D/PwMDAwMDAwMDAwMjI+P/ABwgB/lE0nQAAAAASUVORK5CYII=';

const assetsImg = path.join(__dirname, '..', 'assets', 'images');
fs.mkdirSync(assetsImg, { recursive: true });

const buf = Buffer.from(PNG_BASE64, 'base64');
const lines = ['/** Auto-generated by scripts/generate-images.js */', 'export const BACKGROUND_IMAGES = ['];

for (let i = 1; i <= 100; i++) {
  const name = `motivation-${String(i).padStart(3, '0')}.png`;
  fs.writeFileSync(path.join(assetsImg, name), buf);
  lines.push(`  require('../../assets/images/${name}'),`);
}
lines.push('];');
lines.push(`export const TOTAL_IMAGES = ${100};`);

const mapPath = path.join(__dirname, '..', 'src', 'assets', 'imageMap.js');
fs.mkdirSync(path.dirname(mapPath), { recursive: true });
fs.writeFileSync(mapPath, lines.join('\n') + '\n', 'utf8');
console.log(`Wrote 100 PNGs to ${assetsImg}`);
console.log(`Wrote ${mapPath}`);
